# Generated by Django 4.2.3 on 2023-07-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='uploads/', verbose_name='첨부 파일')),
                ('desc', models.CharField(max_length=512)),
            ],
        ),
    ]
